//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public Game()
        {
            this.Rounds = new HashSet<Round>();
        }
    
        public System.Guid ID { get; set; }
        public string OpponentName { get; set; }
        public Nullable<int> PointsToWin { get; set; }
        public Nullable<int> MaxRounds { get; set; }
        public Nullable<int> DynamiteCount { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<int> GameNumber { get; set; }
    
        public virtual ICollection<Round> Rounds { get; set; }
    }
}
