//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Round
    {
        public System.Guid ID { get; set; }
        public string OurMove { get; set; }
        public string TheirMove { get; set; }
        public System.Guid GameID { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<int> RoundNumber { get; set; }
    
        public virtual Game Game { get; set; }
    }
}
